"""
 Copyright (C) 2025 boogie

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import ctypes
import enum

from v4l2codecs import log
from v4l2codecs import clib

from v4l2codecs.av import util


class EnumCodecID(clib.CIntEnum):
    class _enum_(enum.IntEnum):
        AV_CODEC_ID_NONE = enum.auto()
        AV_CODEC_ID_MPEG1VIDEO = enum.auto()
        AV_CODEC_ID_MPEG2VIDEO = enum.auto()
        AV_CODEC_ID_H261 = enum.auto()
        AV_CODEC_ID_H263 = enum.auto()
        AV_CODEC_ID_RV10 = enum.auto()
        AV_CODEC_ID_RV20 = enum.auto()
        AV_CODEC_ID_MJPEG = enum.auto()
        AV_CODEC_ID_MJPEGB = enum.auto()
        AV_CODEC_ID_LJPEG = enum.auto()
        AV_CODEC_ID_SP5X = enum.auto()
        AV_CODEC_ID_JPEGLS = enum.auto()
        AV_CODEC_ID_MPEG4 = enum.auto()
        AV_CODEC_ID_RAWVIDEO = enum.auto()
        AV_CODEC_ID_MSMPEG4V1 = enum.auto()
        AV_CODEC_ID_MSMPEG4V2 = enum.auto()
        AV_CODEC_ID_MSMPEG4V3 = enum.auto()
        AV_CODEC_ID_WMV1 = enum.auto()
        AV_CODEC_ID_WMV2 = enum.auto()
        AV_CODEC_ID_H263P = enum.auto()
        AV_CODEC_ID_H263I = enum.auto()
        AV_CODEC_ID_FLV1 = enum.auto()
        AV_CODEC_ID_SVQ1 = enum.auto()
        AV_CODEC_ID_SVQ3 = enum.auto()
        AV_CODEC_ID_DVVIDEO = enum.auto()
        AV_CODEC_ID_HUFFYUV = enum.auto()
        AV_CODEC_ID_CYUV = enum.auto()
        AV_CODEC_ID_H264 = enum.auto()
        AV_CODEC_ID_INDEO3 = enum.auto()
        AV_CODEC_ID_VP3 = enum.auto()
        AV_CODEC_ID_THEORA = enum.auto()
        AV_CODEC_ID_ASV1 = enum.auto()
        AV_CODEC_ID_ASV2 = enum.auto()
        AV_CODEC_ID_FFV1 = enum.auto()
        AV_CODEC_ID_4XM = enum.auto()
        AV_CODEC_ID_VCR1 = enum.auto()
        AV_CODEC_ID_CLJR = enum.auto()
        AV_CODEC_ID_MDEC = enum.auto()
        AV_CODEC_ID_ROQ = enum.auto()
        AV_CODEC_ID_INTERPLAY_VIDEO = enum.auto()
        AV_CODEC_ID_XAN_WC3 = enum.auto()
        AV_CODEC_ID_XAN_WC4 = enum.auto()
        AV_CODEC_ID_RPZA = enum.auto()
        AV_CODEC_ID_CINEPAK = enum.auto()
        AV_CODEC_ID_WS_VQA = enum.auto()
        AV_CODEC_ID_MSRLE = enum.auto()
        AV_CODEC_ID_MSVIDEO1 = enum.auto()
        AV_CODEC_ID_IDCIN = enum.auto()
        AV_CODEC_ID_8BPS = enum.auto()
        AV_CODEC_ID_SMC = enum.auto()
        AV_CODEC_ID_FLIC = enum.auto()
        AV_CODEC_ID_TRUEMOTION1 = enum.auto()
        AV_CODEC_ID_VMDVIDEO = enum.auto()
        AV_CODEC_ID_MSZH = enum.auto()
        AV_CODEC_ID_ZLIB = enum.auto()
        AV_CODEC_ID_QTRLE = enum.auto()
        AV_CODEC_ID_TSCC = enum.auto()
        AV_CODEC_ID_ULTI = enum.auto()
        AV_CODEC_ID_QDRAW = enum.auto()
        AV_CODEC_ID_VIXL = enum.auto()
        AV_CODEC_ID_QPEG = enum.auto()
        AV_CODEC_ID_PNG = enum.auto()
        AV_CODEC_ID_PPM = enum.auto()
        AV_CODEC_ID_PBM = enum.auto()
        AV_CODEC_ID_PGM = enum.auto()
        AV_CODEC_ID_PGMYUV = enum.auto()
        AV_CODEC_ID_PAM = enum.auto()
        AV_CODEC_ID_FFVHUFF = enum.auto()
        AV_CODEC_ID_RV30 = enum.auto()
        AV_CODEC_ID_RV40 = enum.auto()
        AV_CODEC_ID_VC1 = enum.auto()
        AV_CODEC_ID_WMV3 = enum.auto()
        AV_CODEC_ID_LOCO = enum.auto()
        AV_CODEC_ID_WNV1 = enum.auto()
        AV_CODEC_ID_AASC = enum.auto()
        AV_CODEC_ID_INDEO2 = enum.auto()
        AV_CODEC_ID_FRAPS = enum.auto()
        AV_CODEC_ID_TRUEMOTION2 = enum.auto()
        AV_CODEC_ID_BMP = enum.auto()
        AV_CODEC_ID_CSCD = enum.auto()
        AV_CODEC_ID_MMVIDEO = enum.auto()
        AV_CODEC_ID_ZMBV = enum.auto()
        AV_CODEC_ID_AVS = enum.auto()
        AV_CODEC_ID_SMACKVIDEO = enum.auto()
        AV_CODEC_ID_NUV = enum.auto()
        AV_CODEC_ID_KMVC = enum.auto()
        AV_CODEC_ID_FLASHSV = enum.auto()
        AV_CODEC_ID_CAVS = enum.auto()
        AV_CODEC_ID_JPEG2000 = enum.auto()
        AV_CODEC_ID_VMNC = enum.auto()
        AV_CODEC_ID_VP5 = enum.auto()
        AV_CODEC_ID_VP6 = enum.auto()
        AV_CODEC_ID_VP6F = enum.auto()
        AV_CODEC_ID_TARGA = enum.auto()
        AV_CODEC_ID_DSICINVIDEO = enum.auto()
        AV_CODEC_ID_TIERTEXSEQVIDEO = enum.auto()
        AV_CODEC_ID_TIFF = enum.auto()
        AV_CODEC_ID_GIF = enum.auto()
        AV_CODEC_ID_DXA = enum.auto()
        AV_CODEC_ID_DNXHD = enum.auto()
        AV_CODEC_ID_THP = enum.auto()
        AV_CODEC_ID_SGI = enum.auto()
        AV_CODEC_ID_C93 = enum.auto()
        AV_CODEC_ID_BETHSOFTVID = enum.auto()
        AV_CODEC_ID_PTX = enum.auto()
        AV_CODEC_ID_TXD = enum.auto()
        AV_CODEC_ID_VP6A = enum.auto()
        AV_CODEC_ID_AMV = enum.auto()
        AV_CODEC_ID_VB = enum.auto()
        AV_CODEC_ID_PCX = enum.auto()
        AV_CODEC_ID_SUNRAST = enum.auto()
        AV_CODEC_ID_INDEO4 = enum.auto()
        AV_CODEC_ID_INDEO5 = enum.auto()
        AV_CODEC_ID_MIMIC = enum.auto()
        AV_CODEC_ID_RL2 = enum.auto()
        AV_CODEC_ID_ESCAPE124 = enum.auto()
        AV_CODEC_ID_DIRAC = enum.auto()
        AV_CODEC_ID_BFI = enum.auto()
        AV_CODEC_ID_CMV = enum.auto()
        AV_CODEC_ID_MOTIONPIXELS = enum.auto()
        AV_CODEC_ID_TGV = enum.auto()
        AV_CODEC_ID_TGQ = enum.auto()
        AV_CODEC_ID_TQI = enum.auto()
        AV_CODEC_ID_AURA = enum.auto()
        AV_CODEC_ID_AURA2 = enum.auto()
        AV_CODEC_ID_V210X = enum.auto()
        AV_CODEC_ID_TMV = enum.auto()
        AV_CODEC_ID_V210 = enum.auto()
        AV_CODEC_ID_DPX = enum.auto()
        AV_CODEC_ID_MAD = enum.auto()
        AV_CODEC_ID_FRWU = enum.auto()
        AV_CODEC_ID_FLASHSV2 = enum.auto()
        AV_CODEC_ID_CDGRAPHICS = enum.auto()
        AV_CODEC_ID_R210 = enum.auto()
        AV_CODEC_ID_ANM = enum.auto()
        AV_CODEC_ID_BINKVIDEO = enum.auto()
        AV_CODEC_ID_IFF_ILBM = enum.auto()
        AV_CODEC_ID_KGV1 = enum.auto()
        AV_CODEC_ID_YOP = enum.auto()
        AV_CODEC_ID_VP8 = enum.auto()
        AV_CODEC_ID_PICTOR = enum.auto()
        AV_CODEC_ID_ANSI = enum.auto()
        AV_CODEC_ID_A64_MULTI = enum.auto()
        AV_CODEC_ID_A64_MULTI5 = enum.auto()
        AV_CODEC_ID_R10K = enum.auto()
        AV_CODEC_ID_MXPEG = enum.auto()
        AV_CODEC_ID_LAGARITH = enum.auto()
        AV_CODEC_ID_PRORES = enum.auto()
        AV_CODEC_ID_JV = enum.auto()
        AV_CODEC_ID_DFA = enum.auto()
        AV_CODEC_ID_WMV3IMAGE = enum.auto()
        AV_CODEC_ID_VC1IMAGE = enum.auto()
        AV_CODEC_ID_UTVIDEO = enum.auto()
        AV_CODEC_ID_BMV_VIDEO = enum.auto()
        AV_CODEC_ID_VBLE = enum.auto()
        AV_CODEC_ID_DXTORY = enum.auto()
        AV_CODEC_ID_V410 = enum.auto()
        AV_CODEC_ID_XWD = enum.auto()
        AV_CODEC_ID_CDXL = enum.auto()
        AV_CODEC_ID_XBM = enum.auto()
        AV_CODEC_ID_ZEROCODEC = enum.auto()
        AV_CODEC_ID_MSS1 = enum.auto()
        AV_CODEC_ID_MSA1 = enum.auto()
        AV_CODEC_ID_TSCC2 = enum.auto()
        AV_CODEC_ID_MTS2 = enum.auto()
        AV_CODEC_ID_CLLC = enum.auto()
        AV_CODEC_ID_MSS2 = enum.auto()
        AV_CODEC_ID_VP9 = enum.auto()
        AV_CODEC_ID_AIC = enum.auto()
        AV_CODEC_ID_ESCAPE130 = enum.auto()
        AV_CODEC_ID_G2M = enum.auto()
        AV_CODEC_ID_WEBP = enum.auto()
        AV_CODEC_ID_HNM4_VIDEO = enum.auto()
        AV_CODEC_ID_HEVC = enum.auto()
        AV_CODEC_ID_FIC = enum.auto()
        AV_CODEC_ID_ALIAS_PIX = enum.auto()
        AV_CODEC_ID_BRENDER_PIX = enum.auto()
        AV_CODEC_ID_PAF_VIDEO = enum.auto()
        AV_CODEC_ID_EXR = enum.auto()
        AV_CODEC_ID_VP7 = enum.auto()
        AV_CODEC_ID_SANM = enum.auto()
        AV_CODEC_ID_SGIRLE = enum.auto()
        AV_CODEC_ID_MVC1 = enum.auto()
        AV_CODEC_ID_MVC2 = enum.auto()
        AV_CODEC_ID_HQX = enum.auto()
        AV_CODEC_ID_TDSC = enum.auto()
        AV_CODEC_ID_HQ_HQA = enum.auto()
        AV_CODEC_ID_HAP = enum.auto()
        AV_CODEC_ID_DDS = enum.auto()
        AV_CODEC_ID_DXV = enum.auto()
        AV_CODEC_ID_SCREENPRESSO = enum.auto()
        AV_CODEC_ID_RSCC = enum.auto()
        AV_CODEC_ID_AVS2 = enum.auto()
        AV_CODEC_ID_PGX = enum.auto()
        AV_CODEC_ID_AVS3 = enum.auto()
        AV_CODEC_ID_MSP2 = enum.auto()
        AV_CODEC_ID_VVC = enum.auto()
        AV_CODEC_ID_Y41P = enum.auto()
        AV_CODEC_ID_AVRP = enum.auto()
        AV_CODEC_ID_012V = enum.auto()
        AV_CODEC_ID_AVUI = enum.auto()
        AV_CODEC_ID_TARGA_Y216 = enum.auto()
        AV_CODEC_ID_V308 = enum.auto()
        AV_CODEC_ID_V408 = enum.auto()
        AV_CODEC_ID_YUV4 = enum.auto()
        AV_CODEC_ID_AVRN = enum.auto()
        AV_CODEC_ID_CPIA = enum.auto()
        AV_CODEC_ID_XFACE = enum.auto()
        AV_CODEC_ID_SNOW = enum.auto()
        AV_CODEC_ID_SMVJPEG = enum.auto()
        AV_CODEC_ID_APNG = enum.auto()
        AV_CODEC_ID_DAALA = enum.auto()
        AV_CODEC_ID_CFHD = enum.auto()
        AV_CODEC_ID_TRUEMOTION2RT = enum.auto()
        AV_CODEC_ID_M101 = enum.auto()
        AV_CODEC_ID_MAGICYUV = enum.auto()
        AV_CODEC_ID_SHEERVIDEO = enum.auto()
        AV_CODEC_ID_YLC = enum.auto()
        AV_CODEC_ID_PSD = enum.auto()
        AV_CODEC_ID_PIXLET = enum.auto()
        AV_CODEC_ID_SPEEDHQ = enum.auto()
        AV_CODEC_ID_FMVC = enum.auto()
        AV_CODEC_ID_SCPR = enum.auto()
        AV_CODEC_ID_CLEARVIDEO = enum.auto()
        AV_CODEC_ID_XPM = enum.auto()
        AV_CODEC_ID_AV1 = enum.auto()
        AV_CODEC_ID_BITPACKED = enum.auto()
        AV_CODEC_ID_MSCC = enum.auto()
        AV_CODEC_ID_SRGC = enum.auto()
        AV_CODEC_ID_SVG = enum.auto()
        AV_CODEC_ID_GDV = enum.auto()
        AV_CODEC_ID_FITS = enum.auto()
        AV_CODEC_ID_IMM4 = enum.auto()
        AV_CODEC_ID_PROSUMER = enum.auto()
        AV_CODEC_ID_MWSC = enum.auto()
        AV_CODEC_ID_WCMV = enum.auto()
        AV_CODEC_ID_RASC = enum.auto()
        AV_CODEC_ID_HYMT = enum.auto()
        AV_CODEC_ID_ARBC = enum.auto()
        AV_CODEC_ID_AGM = enum.auto()
        AV_CODEC_ID_LSCR = enum.auto()
        AV_CODEC_ID_VP4 = enum.auto()
        AV_CODEC_ID_IMM5 = enum.auto()
        AV_CODEC_ID_MVDV = enum.auto()
        AV_CODEC_ID_MVHA = enum.auto()
        AV_CODEC_ID_CDTOONS = enum.auto()
        AV_CODEC_ID_MV30 = enum.auto()
        AV_CODEC_ID_NOTCHLC = enum.auto()
        AV_CODEC_ID_PFM = enum.auto()
        AV_CODEC_ID_MOBICLIP = enum.auto()
        AV_CODEC_ID_PHOTOCD = enum.auto()
        AV_CODEC_ID_IPU = enum.auto()
        AV_CODEC_ID_ARGO = enum.auto()
        AV_CODEC_ID_CRI = enum.auto()
        AV_CODEC_ID_SIMBIOSIS_IMX = enum.auto()
        AV_CODEC_ID_SGA_VIDEO = enum.auto()
        AV_CODEC_ID_GEM = enum.auto()
        AV_CODEC_ID_VBN = enum.auto()
        AV_CODEC_ID_JPEGXL = enum.auto()
        AV_CODEC_ID_QOI = enum.auto()
        AV_CODEC_ID_PHM = enum.auto()
        AV_CODEC_ID_RADIANCE_HDR = enum.auto()
        AV_CODEC_ID_WBMP = enum.auto()
        AV_CODEC_ID_MEDIA100 = enum.auto()
        AV_CODEC_ID_VQC = enum.auto()
        AV_CODEC_ID_PDV = enum.auto()
        AV_CODEC_ID_EVC = enum.auto()
        AV_CODEC_ID_RTV1 = enum.auto()
        AV_CODEC_ID_VMIX = enum.auto()
        AV_CODEC_ID_LEAD = enum.auto()
        AV_CODEC_ID_FIRST_AUDIO = 0x10000 = enum.auto()
        AV_CODEC_ID_PCM_S16LE = 0x10000 = enum.auto()
        AV_CODEC_ID_PCM_S16BE = enum.auto()
        AV_CODEC_ID_PCM_U16LE = enum.auto()
        AV_CODEC_ID_PCM_U16BE = enum.auto()
        AV_CODEC_ID_PCM_S8 = enum.auto()
        AV_CODEC_ID_PCM_U8 = enum.auto()
        AV_CODEC_ID_PCM_MULAW = enum.auto()
        AV_CODEC_ID_PCM_ALAW = enum.auto()
        AV_CODEC_ID_PCM_S32LE = enum.auto()
        AV_CODEC_ID_PCM_S32BE = enum.auto()
        AV_CODEC_ID_PCM_U32LE = enum.auto()
        AV_CODEC_ID_PCM_U32BE = enum.auto()
        AV_CODEC_ID_PCM_S24LE = enum.auto()
        AV_CODEC_ID_PCM_S24BE = enum.auto()
        AV_CODEC_ID_PCM_U24LE = enum.auto()
        AV_CODEC_ID_PCM_U24BE = enum.auto()
        AV_CODEC_ID_PCM_S24DAUD = enum.auto()
        AV_CODEC_ID_PCM_ZORK = enum.auto()
        AV_CODEC_ID_PCM_S16LE_PLANAR = enum.auto()
        AV_CODEC_ID_PCM_DVD = enum.auto()
        AV_CODEC_ID_PCM_F32BE = enum.auto()
        AV_CODEC_ID_PCM_F32LE = enum.auto()
        AV_CODEC_ID_PCM_F64BE = enum.auto()
        AV_CODEC_ID_PCM_F64LE = enum.auto()
        AV_CODEC_ID_PCM_BLURAY = enum.auto()
        AV_CODEC_ID_PCM_LXF = enum.auto()
        AV_CODEC_ID_S302M = enum.auto()
        AV_CODEC_ID_PCM_S8_PLANAR = enum.auto()
        AV_CODEC_ID_PCM_S24LE_PLANAR = enum.auto()
        AV_CODEC_ID_PCM_S32LE_PLANAR = enum.auto()
        AV_CODEC_ID_PCM_S16BE_PLANAR = enum.auto()
        AV_CODEC_ID_PCM_S64LE = enum.auto()
        AV_CODEC_ID_PCM_S64BE = enum.auto()
        AV_CODEC_ID_PCM_F16LE = enum.auto()
        AV_CODEC_ID_PCM_F24LE = enum.auto()
        AV_CODEC_ID_PCM_VIDC = enum.auto()
        AV_CODEC_ID_PCM_SGA = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_QT = 0x11000
        AV_CODEC_ID_ADPCM_IMA_WAV = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_DK3 = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_DK4 = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_WS = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_SMJPEG = enum.auto()
        AV_CODEC_ID_ADPCM_MS = enum.auto()
        AV_CODEC_ID_ADPCM_4XM = enum.auto()
        AV_CODEC_ID_ADPCM_XA = enum.auto()
        AV_CODEC_ID_ADPCM_ADX = enum.auto()
        AV_CODEC_ID_ADPCM_EA = enum.auto()
        AV_CODEC_ID_ADPCM_G726 = enum.auto()
        AV_CODEC_ID_ADPCM_CT = enum.auto()
        AV_CODEC_ID_ADPCM_SWF = enum.auto()
        AV_CODEC_ID_ADPCM_YAMAHA = enum.auto()
        AV_CODEC_ID_ADPCM_SBPRO_4 = enum.auto()
        AV_CODEC_ID_ADPCM_SBPRO_3 = enum.auto()
        AV_CODEC_ID_ADPCM_SBPRO_2 = enum.auto()
        AV_CODEC_ID_ADPCM_THP = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_AMV = enum.auto()
        AV_CODEC_ID_ADPCM_EA_R1 = enum.auto()
        AV_CODEC_ID_ADPCM_EA_R3 = enum.auto()
        AV_CODEC_ID_ADPCM_EA_R2 = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_EA_SEAD = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_EA_EACS = enum.auto()
        AV_CODEC_ID_ADPCM_EA_XAS = enum.auto()
        AV_CODEC_ID_ADPCM_EA_MAXIS_XA = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_ISS = enum.auto()
        AV_CODEC_ID_ADPCM_G722 = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_APC = enum.auto()
        AV_CODEC_ID_ADPCM_VIMA = enum.auto()
        AV_CODEC_ID_ADPCM_AFC = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_OKI = enum.auto()
        AV_CODEC_ID_ADPCM_DTK = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_RAD = enum.auto()
        AV_CODEC_ID_ADPCM_G726LE = enum.auto()
        AV_CODEC_ID_ADPCM_THP_LE = enum.auto()
        AV_CODEC_ID_ADPCM_PSX = enum.auto()
        AV_CODEC_ID_ADPCM_AICA = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_DAT4 = enum.auto()
        AV_CODEC_ID_ADPCM_MTAF = enum.auto()
        AV_CODEC_ID_ADPCM_AGM = enum.auto()
        AV_CODEC_ID_ADPCM_ARGO = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_SSI = enum.auto()
        AV_CODEC_ID_ADPCM_ZORK = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_APM = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_ALP = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_MTF = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_CUNNING = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_MOFLEX = enum.auto()
        AV_CODEC_ID_ADPCM_IMA_ACORN = enum.auto()
        AV_CODEC_ID_ADPCM_XMD = enum.auto()
        AV_CODEC_ID_AMR_NB = 0x12000 = enum.auto()
        AV_CODEC_ID_AMR_WB = enum.auto()
        AV_CODEC_ID_RA_144 = 0x13000
        AV_CODEC_ID_RA_288 = enum.auto()
        AV_CODEC_ID_ROQ_DPCM = 0x14000
        AV_CODEC_ID_INTERPLAY_DPCM = enum.auto()
        AV_CODEC_ID_XAN_DPCM = enum.auto()
        AV_CODEC_ID_SOL_DPCM = enum.auto()
        AV_CODEC_ID_SDX2_DPCM = enum.auto()
        AV_CODEC_ID_GREMLIN_DPCM = enum.auto()
        AV_CODEC_ID_DERF_DPCM = enum.auto()
        AV_CODEC_ID_WADY_DPCM = enum.auto()
        AV_CODEC_ID_CBD2_DPCM = enum.auto()
        AV_CODEC_ID_MP2 = 0x15000
        AV_CODEC_ID_MP3 = enum.auto()
        AV_CODEC_ID_AAC = enum.auto()
        AV_CODEC_ID_AC3 = enum.auto()
        AV_CODEC_ID_DTS = enum.auto()
        AV_CODEC_ID_VORBIS = enum.auto()
        AV_CODEC_ID_DVAUDIO = enum.auto()
        AV_CODEC_ID_WMAV1 = enum.auto()
        AV_CODEC_ID_WMAV2 = enum.auto()
        AV_CODEC_ID_MACE3 = enum.auto()
        AV_CODEC_ID_MACE6 = enum.auto()
        AV_CODEC_ID_VMDAUDIO = enum.auto()
        AV_CODEC_ID_FLAC = enum.auto()
        AV_CODEC_ID_MP3ADU = enum.auto()
        AV_CODEC_ID_MP3ON4 = enum.auto()
        AV_CODEC_ID_SHORTEN = enum.auto()
        AV_CODEC_ID_ALAC = enum.auto()
        AV_CODEC_ID_WESTWOOD_SND1 = enum.auto()
        AV_CODEC_ID_GSM = enum.auto()
        AV_CODEC_ID_QDM2 = enum.auto()
        AV_CODEC_ID_COOK = enum.auto()
        AV_CODEC_ID_TRUESPEECH = enum.auto()
        AV_CODEC_ID_TTA = enum.auto()
        AV_CODEC_ID_SMACKAUDIO = enum.auto()
        AV_CODEC_ID_QCELP = enum.auto()
        AV_CODEC_ID_WAVPACK = enum.auto()
        AV_CODEC_ID_DSICINAUDIO = enum.auto()
        AV_CODEC_ID_IMC = enum.auto()
        AV_CODEC_ID_MUSEPACK7 = enum.auto()
        AV_CODEC_ID_MLP = enum.auto()
        AV_CODEC_ID_GSM_MS = enum.auto()
        AV_CODEC_ID_ATRAC3 = enum.auto()
        AV_CODEC_ID_APE = enum.auto()
        AV_CODEC_ID_NELLYMOSER = enum.auto()
        AV_CODEC_ID_MUSEPACK8 = enum.auto()
        AV_CODEC_ID_SPEEX = enum.auto()
        AV_CODEC_ID_WMAVOICE = enum.auto()
        AV_CODEC_ID_WMAPRO = enum.auto()
        AV_CODEC_ID_WMALOSSLESS = enum.auto()
        AV_CODEC_ID_ATRAC3P = enum.auto()
        AV_CODEC_ID_EAC3 = enum.auto()
        AV_CODEC_ID_SIPR = enum.auto()
        AV_CODEC_ID_MP1 = enum.auto()
        AV_CODEC_ID_TWINVQ = enum.auto()
        AV_CODEC_ID_TRUEHD = enum.auto()
        AV_CODEC_ID_MP4ALS = enum.auto()
        AV_CODEC_ID_ATRAC1 = enum.auto()
        AV_CODEC_ID_BINKAUDIO_RDFT = enum.auto()
        AV_CODEC_ID_BINKAUDIO_DCT = enum.auto()
        AV_CODEC_ID_AAC_LATM = enum.auto()
        AV_CODEC_ID_QDMC = enum.auto()
        AV_CODEC_ID_CELT = enum.auto()
        AV_CODEC_ID_G723_1 = enum.auto()
        AV_CODEC_ID_G729 = enum.auto()
        AV_CODEC_ID_8SVX_EXP = enum.auto()
        AV_CODEC_ID_8SVX_FIB = enum.auto()
        AV_CODEC_ID_BMV_AUDIO = enum.auto()
        AV_CODEC_ID_RALF = enum.auto()
        AV_CODEC_ID_IAC = enum.auto()
        AV_CODEC_ID_ILBC = enum.auto()
        AV_CODEC_ID_OPUS = enum.auto()
        AV_CODEC_ID_COMFORT_NOISE = enum.auto()
        AV_CODEC_ID_TAK = enum.auto()
        AV_CODEC_ID_METASOUND = enum.auto()
        AV_CODEC_ID_PAF_AUDIO = enum.auto()
        AV_CODEC_ID_ON2AVC = enum.auto()
        AV_CODEC_ID_DSS_SP = enum.auto()
        AV_CODEC_ID_CODEC2 = enum.auto()
        AV_CODEC_ID_FFWAVESYNTH = enum.auto()
        AV_CODEC_ID_SONIC = enum.auto()
        AV_CODEC_ID_SONIC_LS = enum.auto()
        AV_CODEC_ID_EVRC = enum.auto()
        AV_CODEC_ID_SMV = enum.auto()
        AV_CODEC_ID_DSD_LSBF = enum.auto()
        AV_CODEC_ID_DSD_MSBF = enum.auto()
        AV_CODEC_ID_DSD_LSBF_PLANAR = enum.auto()
        AV_CODEC_ID_DSD_MSBF_PLANAR = enum.auto()
        AV_CODEC_ID_4GV = enum.auto()
        AV_CODEC_ID_INTERPLAY_ACM = enum.auto()
        AV_CODEC_ID_XMA1 = enum.auto()
        AV_CODEC_ID_XMA2 = enum.auto()
        AV_CODEC_ID_DST = enum.auto()
        AV_CODEC_ID_ATRAC3AL = enum.auto()
        AV_CODEC_ID_ATRAC3PAL = enum.auto()
        AV_CODEC_ID_DOLBY_E = enum.auto()
        AV_CODEC_ID_APTX = enum.auto()
        AV_CODEC_ID_APTX_HD = enum.auto()
        AV_CODEC_ID_SBC = enum.auto()
        AV_CODEC_ID_ATRAC9 = enum.auto()
        AV_CODEC_ID_HCOM = enum.auto()
        AV_CODEC_ID_ACELP_KELVIN = enum.auto()
        AV_CODEC_ID_MPEGH_3D_AUDIO = enum.auto()
        AV_CODEC_ID_SIREN = enum.auto()
        AV_CODEC_ID_HCA = enum.auto()
        AV_CODEC_ID_FASTAUDIO = enum.auto()
        AV_CODEC_ID_MSNSIREN = enum.auto()
        AV_CODEC_ID_DFPWM = enum.auto()
        AV_CODEC_ID_BONK = enum.auto()
        AV_CODEC_ID_MISC4 = enum.auto()
        AV_CODEC_ID_APAC = enum.auto()
        AV_CODEC_ID_FTR = enum.auto()
        AV_CODEC_ID_WAVARC = enum.auto()
        AV_CODEC_ID_RKA = enum.auto()
        AV_CODEC_ID_AC4 = enum.auto()
        AV_CODEC_ID_OSQ = enum.auto()
        AV_CODEC_ID_QOA = enum.auto()
        AV_CODEC_ID_LC3 = enum.auto()
        AV_CODEC_ID_FIRST_SUBTITLE = 0x17000
        AV_CODEC_ID_DVD_SUBTITLE = 0x17000
        AV_CODEC_ID_DVB_SUBTITLE = enum.auto()
        AV_CODEC_ID_TEXT = enum.auto()
        AV_CODEC_ID_XSUB = enum.auto()
        AV_CODEC_ID_SSA = enum.auto()
        AV_CODEC_ID_MOV_TEXT = enum.auto()
        AV_CODEC_ID_HDMV_PGS_SUBTITLE = enum.auto()
        AV_CODEC_ID_DVB_TELETEXT = enum.auto()
        AV_CODEC_ID_SRT = enum.auto()
        AV_CODEC_ID_MICRODVD = enum.auto()
        AV_CODEC_ID_EIA_608 = enum.auto()
        AV_CODEC_ID_JACOSUB = enum.auto()
        AV_CODEC_ID_SAMI = enum.auto()
        AV_CODEC_ID_REALTEXT = enum.auto()
        AV_CODEC_ID_STL = enum.auto()
        AV_CODEC_ID_SUBVIEWER1 = enum.auto()
        AV_CODEC_ID_SUBVIEWER = enum.auto()
        AV_CODEC_ID_SUBRIP = enum.auto()
        AV_CODEC_ID_WEBVTT = enum.auto()
        AV_CODEC_ID_MPL2 = enum.auto()
        AV_CODEC_ID_VPLAYER = enum.auto()
        AV_CODEC_ID_PJS = enum.auto()
        AV_CODEC_ID_ASS = enum.auto()
        AV_CODEC_ID_HDMV_TEXT_SUBTITLE = enum.auto()
        AV_CODEC_ID_TTML = enum.auto()
        AV_CODEC_ID_ARIB_CAPTION = enum.auto()
        AV_CODEC_ID_FIRST_UNKNOWN = 0x18000
        AV_CODEC_ID_TTF = 0x18000
        AV_CODEC_ID_SCTE_35 = enum.auto()
        AV_CODEC_ID_EPG = enum.auto()
        AV_CODEC_ID_BINTEXT = enum.auto()
        AV_CODEC_ID_XBIN = enum.auto()
        AV_CODEC_ID_IDF = enum.auto()
        AV_CODEC_ID_OTF = enum.auto()
        AV_CODEC_ID_SMPTE_KLV = enum.auto()
        AV_CODEC_ID_DVD_NAV = enum.auto()
        AV_CODEC_ID_TIMED_ID3 = enum.auto()
        AV_CODEC_ID_BIN_DATA = enum.auto()
        AV_CODEC_ID_SMPTE_2038 = enum.auto()
        AV_CODEC_ID_LCEVC = enum.auto()
        AV_CODEC_ID_PROBE = 0x19000 = enum.auto()
        AV_CODEC_ID_MPEG2TS = 0x20000 = enum.auto()
        AV_CODEC_ID_MPEG4SYSTEMS = 0x20001 = enum.auto()
        AV_CODEC_ID_FFMETADATA = 0x21000 = enum.auto()
        AV_CODEC_ID_WRAPPED_AVFRAME = 0x21001 = enum.auto()
        AV_CODEC_ID_VNULL = enum.auto()
        AV_CODEC_ID_ANULL = enum.auto()


class StructProfile(ctypes.Structure):
    _fields_ = [
        ('profile', ctypes.c_int),
        ('name', ctypes.c_char_p),
    ]


class StructCodec(ctypes.Structure):
    _fields_ = [
        ('name', ctypes.c_char_p),
        ('long_name', ctypes.POINTER(ctypes.c_char)),
        ('type', util.EnumMediaType),
        ('id', ctypes.c_int),
        ('capabilities', ctypes.c_int),
        ('max_lowres', ctypes.c_uint8),
        ('supported_framerates', ctypes.POINTER(util.StructRational)),
        ('pix_fmts', ctypes.POINTER(util.EnumPixelFormat)),
        ('supported_samplerates', ctypes.POINTER(ctypes.c_int)),
        ('sample_fmts', ctypes.POINTER(util.EnumSampleFormat)),
        ('priv_class', ctypes.c_void_p),
        ('profiles', ctypes.POINTER(StructProfile)),
        ('wrapper_name', ctypes.c_char_p),
        ('ch_layouts', ctypes.POINTER(util.StructChannelLayout)),
    ]


class Lib(clib.CLib):
    _name_ = "avcodec"
    _functions_ = (("avcodec_find_decoder", (EnumCodecID,)), ctypes.POINTER(StructCodec))


log.setlevel(log.DEBUG)
c = Lib()
pass
