"""
 Copyright (C) 2025 boogie

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import ctypes
import enum

from v4l2codecs import log
from v4l2codecs import clib

from v4l2codecs.av import util


class EnumCodecID(clib.CIntEnum):
    class _enum_(enum.IntEnum):
        NONE = 0
        MPEG1VIDEO = enum.auto()
        MPEG2VIDEO = enum.auto()
        H261 = enum.auto()
        H263 = enum.auto()
        RV10 = enum.auto()
        RV20 = enum.auto()
        MJPEG = enum.auto()
        MJPEGB = enum.auto()
        LJPEG = enum.auto()
        SP5X = enum.auto()
        JPEGLS = enum.auto()
        MPEG4 = enum.auto()
        RAWVIDEO = enum.auto()
        MSMPEG4V1 = enum.auto()
        MSMPEG4V2 = enum.auto()
        MSMPEG4V3 = enum.auto()
        WMV1 = enum.auto()
        WMV2 = enum.auto()
        H263P = enum.auto()
        H263I = enum.auto()
        FLV1 = enum.auto()
        SVQ1 = enum.auto()
        SVQ3 = enum.auto()
        DVVIDEO = enum.auto()
        HUFFYUV = enum.auto()
        CYUV = enum.auto()
        H264 = enum.auto()
        INDEO3 = enum.auto()
        VP3 = enum.auto()
        THEORA = enum.auto()
        ASV1 = enum.auto()
        ASV2 = enum.auto()
        FFV1 = enum.auto()
        X4M = enum.auto()
        VCR1 = enum.auto()
        CLJR = enum.auto()
        MDEC = enum.auto()
        ROQ = enum.auto()
        INTERPLAY_VIDEO = enum.auto()
        XAN_WC3 = enum.auto()
        XAN_WC4 = enum.auto()
        RPZA = enum.auto()
        CINEPAK = enum.auto()
        WS_VQA = enum.auto()
        MSRLE = enum.auto()
        MSVIDEO1 = enum.auto()
        IDCIN = enum.auto()
        BPS8 = enum.auto()
        SMC = enum.auto()
        FLIC = enum.auto()
        TRUEMOTION1 = enum.auto()
        VMDVIDEO = enum.auto()
        MSZH = enum.auto()
        ZLIB = enum.auto()
        QTRLE = enum.auto()
        TSCC = enum.auto()
        ULTI = enum.auto()
        QDRAW = enum.auto()
        VIXL = enum.auto()
        QPEG = enum.auto()
        PNG = enum.auto()
        PPM = enum.auto()
        PBM = enum.auto()
        PGM = enum.auto()
        PGMYUV = enum.auto()
        PAM = enum.auto()
        FFVHUFF = enum.auto()
        RV30 = enum.auto()
        RV40 = enum.auto()
        VC1 = enum.auto()
        WMV3 = enum.auto()
        LOCO = enum.auto()
        WNV1 = enum.auto()
        AASC = enum.auto()
        INDEO2 = enum.auto()
        FRAPS = enum.auto()
        TRUEMOTION2 = enum.auto()
        BMP = enum.auto()
        CSCD = enum.auto()
        MMVIDEO = enum.auto()
        ZMBV = enum.auto()
        AVS = enum.auto()
        SMACKVIDEO = enum.auto()
        NUV = enum.auto()
        KMVC = enum.auto()
        FLASHSV = enum.auto()
        CAVS = enum.auto()
        JPEG2000 = enum.auto()
        VMNC = enum.auto()
        VP5 = enum.auto()
        VP6 = enum.auto()
        VP6F = enum.auto()
        TARGA = enum.auto()
        DSICINVIDEO = enum.auto()
        TIERTEXSEQVIDEO = enum.auto()
        TIFF = enum.auto()
        GIF = enum.auto()
        DXA = enum.auto()
        DNXHD = enum.auto()
        THP = enum.auto()
        SGI = enum.auto()
        C93 = enum.auto()
        BETHSOFTVID = enum.auto()
        PTX = enum.auto()
        TXD = enum.auto()
        VP6A = enum.auto()
        AMV = enum.auto()
        VB = enum.auto()
        PCX = enum.auto()
        SUNRAST = enum.auto()
        INDEO4 = enum.auto()
        INDEO5 = enum.auto()
        MIMIC = enum.auto()
        RL2 = enum.auto()
        ESCAPE124 = enum.auto()
        DIRAC = enum.auto()
        BFI = enum.auto()
        CMV = enum.auto()
        MOTIONPIXELS = enum.auto()
        TGV = enum.auto()
        TGQ = enum.auto()
        TQI = enum.auto()
        AURA = enum.auto()
        AURA2 = enum.auto()
        V210X = enum.auto()
        TMV = enum.auto()
        V210 = enum.auto()
        DPX = enum.auto()
        MAD = enum.auto()
        FRWU = enum.auto()
        FLASHSV2 = enum.auto()
        CDGRAPHICS = enum.auto()
        R210 = enum.auto()
        ANM = enum.auto()
        BINKVIDEO = enum.auto()
        IFF_ILBM = enum.auto()
        KGV1 = enum.auto()
        YOP = enum.auto()
        VP8 = enum.auto()
        PICTOR = enum.auto()
        ANSI = enum.auto()
        A64_MULTI = enum.auto()
        A64_MULTI5 = enum.auto()
        R10K = enum.auto()
        MXPEG = enum.auto()
        LAGARITH = enum.auto()
        PRORES = enum.auto()
        JV = enum.auto()
        DFA = enum.auto()
        WMV3IMAGE = enum.auto()
        VC1IMAGE = enum.auto()
        UTVIDEO = enum.auto()
        BMV_VIDEO = enum.auto()
        VBLE = enum.auto()
        DXTORY = enum.auto()
        V410 = enum.auto()
        XWD = enum.auto()
        CDXL = enum.auto()
        XBM = enum.auto()
        ZEROCODEC = enum.auto()
        MSS1 = enum.auto()
        MSA1 = enum.auto()
        TSCC2 = enum.auto()
        MTS2 = enum.auto()
        CLLC = enum.auto()
        MSS2 = enum.auto()
        VP9 = enum.auto()
        AIC = enum.auto()
        ESCAPE130 = enum.auto()
        G2M = enum.auto()
        WEBP = enum.auto()
        HNM4_VIDEO = enum.auto()
        HEVC = enum.auto()
        FIC = enum.auto()
        ALIAS_PIX = enum.auto()
        BRENDER_PIX = enum.auto()
        PAF_VIDEO = enum.auto()
        EXR = enum.auto()
        VP7 = enum.auto()
        SANM = enum.auto()
        SGIRLE = enum.auto()
        MVC1 = enum.auto()
        MVC2 = enum.auto()
        HQX = enum.auto()
        TDSC = enum.auto()
        HQ_HQA = enum.auto()
        HAP = enum.auto()
        DDS = enum.auto()
        DXV = enum.auto()
        SCREENPRESSO = enum.auto()
        RSCC = enum.auto()
        AVS2 = enum.auto()
        PGX = enum.auto()
        AVS3 = enum.auto()
        MSP2 = enum.auto()
        VVC = enum.auto()
        Y41P = enum.auto()
        AVRP = enum.auto()
        O12V = enum.auto()
        AVUI = enum.auto()
        TARGA_Y216 = enum.auto()
        V308 = enum.auto()
        V408 = enum.auto()
        YUV4 = enum.auto()
        AVRN = enum.auto()
        CPIA = enum.auto()
        XFACE = enum.auto()
        SNOW = enum.auto()
        SMVJPEG = enum.auto()
        APNG = enum.auto()
        DAALA = enum.auto()
        CFHD = enum.auto()
        TRUEMOTION2RT = enum.auto()
        M101 = enum.auto()
        MAGICYUV = enum.auto()
        SHEERVIDEO = enum.auto()
        YLC = enum.auto()
        PSD = enum.auto()
        PIXLET = enum.auto()
        SPEEDHQ = enum.auto()
        FMVC = enum.auto()
        SCPR = enum.auto()
        CLEARVIDEO = enum.auto()
        XPM = enum.auto()
        AV1 = enum.auto()
        BITPACKED = enum.auto()
        MSCC = enum.auto()
        SRGC = enum.auto()
        SVG = enum.auto()
        GDV = enum.auto()
        FITS = enum.auto()
        IMM4 = enum.auto()
        PROSUMER = enum.auto()
        MWSC = enum.auto()
        WCMV = enum.auto()
        RASC = enum.auto()
        HYMT = enum.auto()
        ARBC = enum.auto()
        AGM = enum.auto()
        LSCR = enum.auto()
        VP4 = enum.auto()
        IMM5 = enum.auto()
        MVDV = enum.auto()
        MVHA = enum.auto()
        CDTOONS = enum.auto()
        MV30 = enum.auto()
        NOTCHLC = enum.auto()
        PFM = enum.auto()
        MOBICLIP = enum.auto()
        PHOTOCD = enum.auto()
        IPU = enum.auto()
        ARGO = enum.auto()
        CRI = enum.auto()
        SIMBIOSIS_IMX = enum.auto()
        SGA_VIDEO = enum.auto()
        GEM = enum.auto()
        VBN = enum.auto()
        JPEGXL = enum.auto()
        QOI = enum.auto()
        PHM = enum.auto()
        RADIANCE_HDR = enum.auto()
        WBMP = enum.auto()
        MEDIA100 = enum.auto()
        VQC = enum.auto()
        PDV = enum.auto()
        EVC = enum.auto()
        RTV1 = enum.auto()
        VMIX = enum.auto()
        LEAD = enum.auto()
        FIRST_AUDIO = 0x10000
        PCM_S16LE = 0x10000
        PCM_S16BE = enum.auto()
        PCM_U16LE = enum.auto()
        PCM_U16BE = enum.auto()
        PCM_S8 = enum.auto()
        PCM_U8 = enum.auto()
        PCM_MULAW = enum.auto()
        PCM_ALAW = enum.auto()
        PCM_S32LE = enum.auto()
        PCM_S32BE = enum.auto()
        PCM_U32LE = enum.auto()
        PCM_U32BE = enum.auto()
        PCM_S24LE = enum.auto()
        PCM_S24BE = enum.auto()
        PCM_U24LE = enum.auto()
        PCM_U24BE = enum.auto()
        PCM_S24DAUD = enum.auto()
        PCM_ZORK = enum.auto()
        PCM_S16LE_PLANAR = enum.auto()
        PCM_DVD = enum.auto()
        PCM_F32BE = enum.auto()
        PCM_F32LE = enum.auto()
        PCM_F64BE = enum.auto()
        PCM_F64LE = enum.auto()
        PCM_BLURAY = enum.auto()
        PCM_LXF = enum.auto()
        S302M = enum.auto()
        PCM_S8_PLANAR = enum.auto()
        PCM_S24LE_PLANAR = enum.auto()
        PCM_S32LE_PLANAR = enum.auto()
        PCM_S16BE_PLANAR = enum.auto()
        PCM_S64LE = enum.auto()
        PCM_S64BE = enum.auto()
        PCM_F16LE = enum.auto()
        PCM_F24LE = enum.auto()
        PCM_VIDC = enum.auto()
        PCM_SGA = enum.auto()
        ADPCM_IMA_QT = 0x11000
        ADPCM_IMA_WAV = enum.auto()
        ADPCM_IMA_DK3 = enum.auto()
        ADPCM_IMA_DK4 = enum.auto()
        ADPCM_IMA_WS = enum.auto()
        ADPCM_IMA_SMJPEG = enum.auto()
        ADPCM_MS = enum.auto()
        ADPCM_4XM = enum.auto()
        ADPCM_XA = enum.auto()
        ADPCM_ADX = enum.auto()
        ADPCM_EA = enum.auto()
        ADPCM_G726 = enum.auto()
        ADPCM_CT = enum.auto()
        ADPCM_SWF = enum.auto()
        ADPCM_YAMAHA = enum.auto()
        ADPCM_SBPRO_4 = enum.auto()
        ADPCM_SBPRO_3 = enum.auto()
        ADPCM_SBPRO_2 = enum.auto()
        ADPCM_THP = enum.auto()
        ADPCM_IMA_AMV = enum.auto()
        ADPCM_EA_R1 = enum.auto()
        ADPCM_EA_R3 = enum.auto()
        ADPCM_EA_R2 = enum.auto()
        ADPCM_IMA_EA_SEAD = enum.auto()
        ADPCM_IMA_EA_EACS = enum.auto()
        ADPCM_EA_XAS = enum.auto()
        ADPCM_EA_MAXIS_XA = enum.auto()
        ADPCM_IMA_ISS = enum.auto()
        ADPCM_G722 = enum.auto()
        ADPCM_IMA_APC = enum.auto()
        ADPCM_VIMA = enum.auto()
        ADPCM_AFC = enum.auto()
        ADPCM_IMA_OKI = enum.auto()
        ADPCM_DTK = enum.auto()
        ADPCM_IMA_RAD = enum.auto()
        ADPCM_G726LE = enum.auto()
        ADPCM_THP_LE = enum.auto()
        ADPCM_PSX = enum.auto()
        ADPCM_AICA = enum.auto()
        ADPCM_IMA_DAT4 = enum.auto()
        ADPCM_MTAF = enum.auto()
        ADPCM_AGM = enum.auto()
        ADPCM_ARGO = enum.auto()
        ADPCM_IMA_SSI = enum.auto()
        ADPCM_ZORK = enum.auto()
        ADPCM_IMA_APM = enum.auto()
        ADPCM_IMA_ALP = enum.auto()
        ADPCM_IMA_MTF = enum.auto()
        ADPCM_IMA_CUNNING = enum.auto()
        ADPCM_IMA_MOFLEX = enum.auto()
        ADPCM_IMA_ACORN = enum.auto()
        ADPCM_XMD = enum.auto()
        AMR_NB = 0x12000
        AMR_WB = enum.auto()
        RA_144 = 0x13000
        RA_288 = enum.auto()
        ROQ_DPCM = 0x14000
        INTERPLAY_DPCM = enum.auto()
        XAN_DPCM = enum.auto()
        SOL_DPCM = enum.auto()
        SDX2_DPCM = enum.auto()
        GREMLIN_DPCM = enum.auto()
        DERF_DPCM = enum.auto()
        WADY_DPCM = enum.auto()
        CBD2_DPCM = enum.auto()
        MP2 = 0x15000
        MP3 = enum.auto()
        AAC = enum.auto()
        AC3 = enum.auto()
        DTS = enum.auto()
        VORBIS = enum.auto()
        DVAUDIO = enum.auto()
        WMAV1 = enum.auto()
        WMAV2 = enum.auto()
        MACE3 = enum.auto()
        MACE6 = enum.auto()
        VMDAUDIO = enum.auto()
        FLAC = enum.auto()
        MP3ADU = enum.auto()
        MP3ON4 = enum.auto()
        SHORTEN = enum.auto()
        ALAC = enum.auto()
        WESTWOOD_SND1 = enum.auto()
        GSM = enum.auto()
        QDM2 = enum.auto()
        COOK = enum.auto()
        TRUESPEECH = enum.auto()
        TTA = enum.auto()
        SMACKAUDIO = enum.auto()
        QCELP = enum.auto()
        WAVPACK = enum.auto()
        DSICINAUDIO = enum.auto()
        IMC = enum.auto()
        MUSEPACK7 = enum.auto()
        MLP = enum.auto()
        GSM_MS = enum.auto()
        ATRAC3 = enum.auto()
        APE = enum.auto()
        NELLYMOSER = enum.auto()
        MUSEPACK8 = enum.auto()
        SPEEX = enum.auto()
        WMAVOICE = enum.auto()
        WMAPRO = enum.auto()
        WMALOSSLESS = enum.auto()
        ATRAC3P = enum.auto()
        EAC3 = enum.auto()
        SIPR = enum.auto()
        MP1 = enum.auto()
        TWINVQ = enum.auto()
        TRUEHD = enum.auto()
        MP4ALS = enum.auto()
        ATRAC1 = enum.auto()
        BINKAUDIO_RDFT = enum.auto()
        BINKAUDIO_DCT = enum.auto()
        AAC_LATM = enum.auto()
        QDMC = enum.auto()
        CELT = enum.auto()
        G723_1 = enum.auto()
        G729 = enum.auto()
        SVX8_EXP = enum.auto()
        SVX8_FIB = enum.auto()
        BMV_AUDIO = enum.auto()
        RALF = enum.auto()
        IAC = enum.auto()
        ILBC = enum.auto()
        OPUS = enum.auto()
        COMFORT_NOISE = enum.auto()
        TAK = enum.auto()
        METASOUND = enum.auto()
        PAF_AUDIO = enum.auto()
        ON2AVC = enum.auto()
        DSS_SP = enum.auto()
        CODEC2 = enum.auto()
        FFWAVESYNTH = enum.auto()
        SONIC = enum.auto()
        SONIC_LS = enum.auto()
        EVRC = enum.auto()
        SMV = enum.auto()
        DSD_LSBF = enum.auto()
        DSD_MSBF = enum.auto()
        DSD_LSBF_PLANAR = enum.auto()
        DSD_MSBF_PLANAR = enum.auto()
        GV4 = enum.auto()
        INTERPLAY_ACM = enum.auto()
        XMA1 = enum.auto()
        XMA2 = enum.auto()
        DST = enum.auto()
        ATRAC3AL = enum.auto()
        ATRAC3PAL = enum.auto()
        DOLBY_E = enum.auto()
        APTX = enum.auto()
        APTX_HD = enum.auto()
        SBC = enum.auto()
        ATRAC9 = enum.auto()
        HCOM = enum.auto()
        ACELP_KELVIN = enum.auto()
        MPEGH_3D_AUDIO = enum.auto()
        SIREN = enum.auto()
        HCA = enum.auto()
        FASTAUDIO = enum.auto()
        MSNSIREN = enum.auto()
        DFPWM = enum.auto()
        BONK = enum.auto()
        MISC4 = enum.auto()
        APAC = enum.auto()
        FTR = enum.auto()
        WAVARC = enum.auto()
        RKA = enum.auto()
        AC4 = enum.auto()
        OSQ = enum.auto()
        QOA = enum.auto()
        LC3 = enum.auto()
        FIRST_SUBTITLE = 0x17000
        DVD_SUBTITLE = 0x17000
        DVB_SUBTITLE = enum.auto()
        TEXT = enum.auto()
        XSUB = enum.auto()
        SSA = enum.auto()
        MOV_TEXT = enum.auto()
        HDMV_PGS_SUBTITLE = enum.auto()
        DVB_TELETEXT = enum.auto()
        SRT = enum.auto()
        MICRODVD = enum.auto()
        EIA_608 = enum.auto()
        JACOSUB = enum.auto()
        SAMI = enum.auto()
        REALTEXT = enum.auto()
        STL = enum.auto()
        SUBVIEWER1 = enum.auto()
        SUBVIEWER = enum.auto()
        SUBRIP = enum.auto()
        WEBVTT = enum.auto()
        MPL2 = enum.auto()
        VPLAYER = enum.auto()
        PJS = enum.auto()
        ASS = enum.auto()
        HDMV_TEXT_SUBTITLE = enum.auto()
        TTML = enum.auto()
        ARIB_CAPTION = enum.auto()
        FIRST_UNKNOWN = 0x18000
        TTF = 0x18000
        SCTE_35 = enum.auto()
        EPG = enum.auto()
        BINTEXT = enum.auto()
        XBIN = enum.auto()
        IDF = enum.auto()
        OTF = enum.auto()
        SMPTE_KLV = enum.auto()
        DVD_NAV = enum.auto()
        TIMED_ID3 = enum.auto()
        BIN_DATA = enum.auto()
        SMPTE_2038 = enum.auto()
        LCEVC = enum.auto()
        PROBE = 0x19000
        MPEG2TS = 0x20000
        MPEG4SYSTEMS = 0x20001
        FFMETADATA = 0x21000
        WRAPPED_AVFRAME = 0x21001
        VNULL = enum.auto()
        ANULL = enum.auto()


class StructProfile(ctypes.Structure):
    _fields_ = [
        ('profile', ctypes.c_int),
        ('name', ctypes.c_char_p),
    ]


class StructCodec(ctypes.Structure):
    _fields_ = [
        ('name', ctypes.c_char_p),
        ('long_name', ctypes.c_char_p),
        ('type', util.EnumMediaType),
        ('id', EnumCodecID),
        ('capabilities', ctypes.c_int),
        ('max_lowres', ctypes.c_uint8),
        ('supported_framerates', ctypes.POINTER(util.StructRational)),
        ('pix_fmts', ctypes.POINTER(util.EnumPixelFormat)),
        ('supported_samplerates', ctypes.POINTER(ctypes.c_int)),
        ('sample_fmts', ctypes.POINTER(util.EnumSampleFormat)),
        ('priv_class', ctypes.c_void_p),
        ('profiles', ctypes.POINTER(StructProfile)),
        ('wrapper_name', ctypes.c_char_p),
        ('ch_layouts', ctypes.POINTER(util.StructChannelLayout)),
    ]


class Lib(clib.CLib):
    _name_ = "avcodec"
    _functions_ = (("avcodec_find_decoder", (EnumCodecID,), ctypes.POINTER(StructCodec)),
                   ("av_codec_iterate", (ctypes.POINTER(ctypes.c_void_p),), ctypes.POINTER(StructCodec)))


log.setlevel(log.DEBUG)
c = Lib()
p = ctypes.pointer(ctypes.c_void_p())
while True:
    codec = c.av_codec_iterate(p)
    if clib.isnullptr(codec):
        break
    log.LOGGER.info(codec.contents.name.decode())
